spring:
  config:
    import: aws-parameterstore:/pocat/prod/
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      password: ${REDIS_PASSWORD}
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}
        max-redirects: 3
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 8082

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics